### ISSUE TITLE
AssertionError [ERR_ASSERTION]: filePath not found of @bitnoi.se/react-scheduler

### ISSUE THREAD

**Issue by holycrypto** [Bitnoise/react-scheduler#73]
```
AssertionError [ERR_ASSERTION]: filePath not found of @bitnoi.se/react-scheduler
    at /Users/mot/Products/yygg/stage.tatateam.com/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:119:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/mot/Products/yygg/stage.tatateam.com/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:64:103)
    at _next (/Users/mot/Products/yygg/stage.tatateam.com/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:194)
    at /Users/mot/Products/yygg/stage.tatateam.com/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:364
    at new Promise (<anonymous>)
    at /Users/mot/Products/yygg/stage.tatateam.com/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:97
    at figureOutExport (/Users/mot/Products/yygg/stage.tatateam.com/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:129:17)
    at /Users/mot/Products/yygg/stage.tatateam.com/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:184:201
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/mot/Products/yygg/stage.tatateam.com/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:84:103)
    at _next (/Users/mot/Products/yygg/stage.tatateam.com/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:86:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

umijs + antd + @bitnoi.se/react-scheduler

**Comment by BartoszBBitnoise** [comment]
Hello!
Can you share your package.json and file where you use react-scheduler ?
